### ISSUE TITLE
Download failed: Request failed: Forbidden

### ISSUE THREAD

**Issue by benjs2000** [rage/tmc-vscode#252]
Hi,

I'm trying to download the course exercises for Java Programming 1 (by Helsinki Uni) but for most of the exercises I get this error when trying to download?

"Download failed: Request failed: Forbidden"

I managed to download part 1 of the MOOC successfully but even though I have successfully submitted all the exercises I am getting this error for the next part? 

Can anyone advise? Thanks

**Comment by sebazai** [comment]
Hi,

Thank you for the feedback.
We are currently reproducing and investigating this issue.

We will get back to you once we've figured out the cause.

Best regards,
TMC VSCode team.

**Comment by sebazai** [comment]
@benjs2000 We have rolled out a patch to fix this bug. VSCode should check for extension updates automatically and install them. 
Could you please confirm that the issue you described has disappeared? 
The current version of the extension should be 0.1.1

**Comment by benjs2000** [comment]
@sebazai Can confirm this has now been fixed. Thank you very much!
