### ISSUE TITLE
Defining a folder where course sources are downloaded

### ISSUE THREAD

**Issue by jEnbuska** [rage/tmc-vscode#309]
This is a new feature proposal. 

Would it be possible to add a VSCode TMC setting that enables changing where the TMC workspace is created, or some other solution that resolves the same thing?

**Comment by sebazai** [comment]
Hello,

We've been working on this new feature past weeks.
With the next release, hopefully this week, we will have this implemented. Then you are able to change where all the TMC data is stored.
