### ISSUE TITLE
Add a way for user to stop tests that never finish

### ISSUE THREAD

**Issue by Aju100** [rage/tmc-vscode#310]
Hello everyone, I just recently enrolled the data analysis course and I solved few two basic problem. After running the third problem to test, it wasn't working properly in vscode in my ubuntu system.

STEPS TO PRODUCR

- Install tmc through vscode
- Enroll the data analysis course
- go to problem 3 and run the test

* Note: Submission is allowed but test is not.
![problem](https://user-images.githubusercontent.com/29862610/80330417-d16e5f00-8864-11ea-8c67-86976e1ef92a.png)

**Comment by samp3** [comment]
Hello,

We have a (probable) fix for this in today's (27.4.2020) update.

**Comment by Aju100** [comment]
@samp3  sure it will be great for us (students) and other learners. Thank you.

**Comment by jolampi** [comment]
Hello,

We just released a new version of the extension, but this issue will still require some more work. At the moment it seems that the external process running these tests doesn't time out at any point. Hence this issue should occur if one causes an infinite loop in the code and associated tests don't handle it properly. We will look into providing a way to stop the execution in this case.

Meanwhile; you didn't mention whether you made any changes to the exercise template. Can you confirm if an infinite loop was the issue after all?

**Comment by jolampi** [comment]
One way to go about this issue is to [get the process](https://github.com/rage/tmc-vscode/blob/master/src/api/tmc.ts#L521) and map it to some ID. This ID can then be passed to a webview, where pressing a button returns it back. In the case that tests are running in a background, a process timeout may also be desirable.
