### ISSUE TITLE
macOS testing

### ISSUE THREAD

**Issue by sebazai** [rage/tmc-vscode#328]

**Comment by saskeli** [comment]
Some basic testing on MacOS has been done in conjunction with testing the course environment for the 2020 instance of Data analysis with python (https://csmastersuh.github.io/data_analysis_with_python_2020/index.html)

Installation and use according to the instruction in https://www.mooc.fi/en/installation/vscode works as expected and no issues have been found.

**Comment by jolampi** [comment]
Thank you for your report and going over MacOS installation instructions!
