### ISSUE TITLE
Error running tests on exercises

### ISSUE THREAD

**Issue by benjs2000** [rage/tmc-vscode#496]
Hi,

I'm getting the following error when submitting tests for the Java MOOC:

Error:
Langs response missing
Details:
Error stack
Error: Langs response missing
	at c:\Users\Ben\.vscode\extensions\moocfi.test-my-code-0.10.0\dist\extension.js:2:486064
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

I've tried reinstalling both VsCode and the TMC plugin but am still getting this error. I am running Java 11.

Is this a bug? Thanks

**Comment by jolampi** [comment]
Hi @benjs2000, I'm sorry to hear that you are having issues with the extension.

It seems that something is failing when running local tests. Unfortunately I'm unable to replicate the issue. Could you please provide the following details?
- Exact name of the course and organization that it belongs to.
- From the left-side icon, go to the Settings page. Make sure that logging is set to verbose and make them visible by clicking "show logs."
  - Attempt to replicate the issue and provide as exhaustive logs as possible.
  - The insider toggle shouldn't matter when running local tests, but you may toggle it to see if it has any effect.

You can also try to rollback the extension to version 0.9.2 and see if the issue still happens (as an insider). [Check this article to see how.](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) If you do decide to rollback, please make sure that VSCode is restarted afterwards. Please also be aware that the old workspace will also need to be reopened.

**Comment by benjs2000** [comment]
Thanks for your help. I ended up resolving it by completely reinstalling VSCode, all settings, and the JDK.

**Comment by jolampi** [comment]
Glad to hear that you got it working.

There shouldn't be any need to reinstall anything when using the plugin, except maybe if updating from a really old version. However, without further details I will close this issue.
