### ISSUE TITLE
Compatibility changes for TMC Langs 0.5.0

### ISSUE THREAD

**Issue by nygrenh** [rage/tmc-vscode#546]
vscoden python plugin antaa jossain tapauksissa erilaisen virheilmon kuin tmc-cli (ja tmc:n serveri).
esim. tämä palautus  https://tmc.mooc.fi/submissions/8766823 tuottaa virheen "list index out of range" vscodessa.
ja oppilas ei saanut samaa virhetta kun kokeili tmc testia komentorivilla.
olisikohan niin, etta vscode plugin olettaa jotain liikaa .tmc_test_results.json :sta.

**Comment by jolampi** [comment]
This is fixed in TMC Langs 0.5.0 but requires some compatibility changes.
