### ISSUE TITLE
TMC plugin made available in open-vsx marketplace

### ISSUE THREAD

**Issue by viipu** [rage/tmc-vscode#564]
**Is your feature request related to a problem? Please describe.**
If using an open source version based on vscode, e.g. the arch linux default `code` package, the Microsoft Visual Studio Marketplace is not available (at least by default). Instead, the open-vsx marketplace is specified in `product.json`. The TMC plugin is not available on this alternative marketplace. It is not an entirely trivial task to change this setting, and the setting is reset with every update (thus barring future updates to extensions installed from the MS marketplace). Besides, there are reasons why some people would choose not to use the MS marketplace, and it is also unclear whether the terms of the marketplace even allow it to be used with an open source version of the software.  
See discussion here: https://wiki.archlinux.org/index.php/Visual_Studio_Code#No_extensions_found  

**Describe the solution you'd like**
TMC plugin also available in the open-vsx marketplace, https://open-vsx.org/

**Describe alternatives you've considered**
Workaround (although the `product.json` path is not the same as the one described here, might be something like `/usr/lib/code/product.json`): https://github.com/VSCodium/vscodium/issues/418#issuecomment-643664182
Quick fix: something in the mooc.fi installation instructions covering this? Took me quite a while to figure out what was wrong when I first tried to install the extension and couldn't find it. So a quick paragraph (in the Linux section) here might go a long way: https://www.mooc.fi/fi/installation/vscode  

**Additional context**
Problem is by no means unique to this extension; e.g. the Python extension has caused me problems when the open-vsx version is not updated as reliably. So this is part of a bigger discussion, partly to do with using proprietary products that do not fully comply with the OSS ethos.  
Also relevant: https://github.com/microsoft/vscode/issues/31168

**Comment by jolampi** [comment]
Hi @viipu,

Thank you for bringing this issue to our attention. We will forward this request and investigate options available to us.

**Comment by jolampi** [comment]
The extension is now also available at https://open-vsx.org/extension/moocfi/test-my-code
