### ISSUE TITLE
Tehtävän tarkastaminen visual studio codella

### ISSUE THREAD

**Issue by BlackMorphine** [rage/tmc-vscode#613]
Yritän testata visual studio codessa tehtävää Hello Visual Studio Code
mutta tulee kuvassa näkyvä virheilmoitus.

mitä pitäisi tehdä?

![image](https://user-images.githubusercontent.com/42510680/118767718-cd094f80-b886-11eb-85f1-207e46d6885f.png)

**Comment by sebazai** [comment]
Hei,

Olethan ladannut ja avannut tehtävät TMC-liitännäisen kautta?
Täältä löytyy ohjeet: https://www.mooc.fi/en/installation/vscode#select-organization

**Comment by BlackMorphine** [comment]
joo sain ton toimimaan

**Comment by sebazai** [comment]
Hieno homma! Mukavaa koodailua.
