### ISSUE TITLE
Cant download any exercises , keeps on loading , never loads any option, none of the commands work

### ISSUE THREAD

**Issue by rajkumar-2** [rage/tmc-vscode#615]
**Describe the bug**
when using visual studio code to run some tests on an exercise, a unique error popped up, and now opening the TMC tab wont even show any courses or exercises to download.

**To Reproduce**
1. install TMC on VSC
2. open the TMC Tab
3. try to use any shortcuts 
4. See error - command "tmcTreeView.refreshCourses" not found.

**Expected behavior**
i expected to download exercises , run tests ,  or use anything from the extension

**Screenshots**
![2021-05-21 (1)_LI](https://user-images.githubusercontent.com/76872951/119977232-cc369300-bfd5-11eb-8bc4-e23214a5387e.jpg)

**Desktop (please complete the following information):**
 - Windows 10 Home
 - VSCode Version 1.56  ( just got updated as  of writing this post (still doesn't work))
 - TMC Extension Version 2.0.2
 - no other extensions (new to coding)

**TMC Extension logs**
does not let me even open settings

**Additional context**
I have been using netbeans till now the problem started 10 days ago 
also new to github tried to find a solution but failed 
netbeans working for me but I prefer using VSC

**Comment by jolampi** [comment]
Hello,

We are sorry to hear that you are having issues with TestMyCode extension. That error seems to be caused by an incorrect assumption that the extension is already running properly.

The actual issue seems to be that the extension is failing to start. If you've used the it successfully prior to this issue occurring, please navigate to `C:\Users\{USERNAME}\AppData\Roaming\Code\User\globalStorage\moocfi.test-my-code\` and remove the entire `cli` folder. Start VS Code afterwards and see if that helps. Note that the `AppData` folder is hidden by default.

If removing the folder worked, please consider adding an exception for the entire folder it in your antivirus program.

In any other case, please provide the extension logs. You can get them from the Output-tab in the lower panel.
![image](https://user-images.githubusercontent.com/36279434/120160601-16e72380-c1ff-11eb-9bc9-bbc778de15a1.png)

**Comment by rajkumar-2** [comment]
> Hello,
> 
> We are sorry to hear that you are having issues with TestMyCode extension. That error seems to be caused by an incorrect assumption that the extension is already running properly.
> 
> The actual issue seems to be that the extension is failing to start. If you've used the it successfully prior to this issue occurring, please navigate to `C:\Users\{USERNAME}\AppData\Roaming\Code\User\globalStorage\moocfi.test-my-code\` and remove the entire `cli` folder. Start VS Code afterwards and see if that helps. Note that the `AppData` folder is hidden by default.
> 
> If removing the folder worked, please consider adding an exception for the entire folder it in your antivirus program.
> 
> In any other case, please provide the extension logs. You can get them from the Output-tab in the lower panel.
> ![image](https://user-images.githubusercontent.com/36279434/120160601-16e72380-c1ff-11eb-9bc9-bbc778de15a1.png)

the problem persists 

and below are the logs




The extension logs

[2021-05-31 11:20:18:609] [INFO] Starting moocfi.test-my-code in "production" mode.
[2021-05-31 11:20:18:609] [INFO] Visual Studio Code version: 1.56.2
[2021-05-31 11:20:18:609] [INFO] moocfi.test-my-code version: 2.0.2
[2021-05-31 11:20:18:609] [INFO] Currently open workspace: undefined
[2021-05-31 11:20:18:609] [INFO] Platform win32 Arch x64
[2021-05-31 11:20:18:610] [INFO] TMC-Langs version: tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe
[2021-05-31 11:20:18:616] [INFO] Downloading TMC-langs from https://download.mooc.fi/tmc-langs-rust/tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe to c:\Users\raj kumar\AppData\Roaming\Code\User\globalStorage\moocfi.test-my-code\cli\tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe
[2021-05-31 11:20:26:949] [INFO] Run: "c:\\Users\\raj kumar\\AppData\\Roaming\\Code\\User\\globalStorage\\moocfi.test-my-code\\cli\\tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe" "core" "--client-name" "vscode_plugin" "--client-version" "2.0.2" "logged-in"
[2021-05-31 11:20:27:112] [INFO] Run: "c:\\Users\\raj kumar\\AppData\\Roaming\\Code\\User\\globalStorage\\moocfi.test-my-code\\cli\\tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe" "settings" "--client-name" "vscode_plugin" "get" "projects-dir"

**Comment by rajkumar-2** [comment]
Hi,
the problem still persists
ive delete the cli folder and reopened VSC still the courses don't load
I thought I needed TMC to work to use the extension logs ( beginner to
programming ) so thankyou for telling me how to use the logs,

here are those logs
[2021-05-31 11:20:18:609] [INFO] Starting moocfi.test-my-code in
"production" mode.
[2021-05-31 11:20:18:609] [INFO] Visual Studio Code version: 1.56.2
[2021-05-31 11:20:18:609] [INFO] moocfi.test-my-code version: 2.0.2
[2021-05-31 11:20:18:609] [INFO] Currently open workspace: undefined
[2021-05-31 11:20:18:609] [INFO] Platform win32 Arch x64
[2021-05-31 11:20:18:610] [INFO] TMC-Langs version:
tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe
[2021-05-31 11:20:18:616] [INFO] Downloading TMC-langs from
https://download.mooc.fi/tmc-langs-rust/tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe
to
c:\Users\raj
kumar\AppData\Roaming\Code\User\globalStorage\moocfi.test-my-code\cli\tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe
[2021-05-31 11:20:26:949] [INFO] Run: "c:\Users\raj
kumar\AppData\Roaming\Code\User\globalStorage\moocfi.test-my-code\cli\tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe"
"core" "--client-name" "vscode_plugin" "--client-version" "2.0.2"
"logged-in"
[2021-05-31 11:20:27:112] [INFO] Run: "c:\Users\raj
kumar\AppData\Roaming\Code\User\globalStorage\moocfi.test-my-code\cli\tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe"
"settings" "--client-name" "vscode_plugin" "get" "projects-dir"



thanks again for your time.

**Comment by jolampi** [comment]
Could you copy the line
`"c:\Users\raj
kumar\AppData\Roaming\Code\User\globalStorage\moocfi.test-my-code\cli\tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe"
"settings" "--client-name" "vscode_plugin" "get" "projects-dir"`
in its entirety to Command Prompt and run it to see if there are any sensible response? You can open it in VS Code for example from the drop down menu on the terminal tab. Please note that this won't work on PowerShell as the syntax is incompatible.
![image](https://user-images.githubusercontent.com/36279434/120291915-7bbc7f80-c2cc-11eb-8a44-5b624304e7d0.png)

**Comment by rajkumar-2** [comment]
> Could you copy the line
> `"c:\Users\raj kumar\AppData\Roaming\Code\User\globalStorage\moocfi.test-my-code\cli\tmc-langs-cli-x86_64-pc-windows-msvc-0.11.1.exe" "settings" "--client-name" "vscode_plugin" "get" "projects-dir"`
> in its entirety to Command Prompt and run it to see if there are any sensible response? You can open it in VS Code for example from the drop down menu on the terminal tab. Please note that this won't work on PowerShell as the syntax is incompatible.
> ![image](https://user-images.githubusercontent.com/36279434/120291915-7bbc7f80-c2cc-11eb-8a44-5b624304e7d0.png)

![2021-06-01](https://user-images.githubusercontent.com/76872951/120310053-948c5b80-c2f3-11eb-828b-bf26504249dd.png)

**Comment by rajkumar-2** [comment]
[image: 2021-06-01.png]

**Comment by rajkumar-2** [comment]
@jolampi 
the out put showed the location of the tmc file so i deleted it now it works

**Comment by rajkumar-2** [comment]
deleting the tmc file helped now thanks again.

**Comment by jolampi** [comment]
Good to hear that you got it working! It is a bit unfortunate though that we weren't able to figure out the actual culprit. Output data in your previous image seemed valid after all.

Happy coding!
