### ISSUE TITLE
TestMyCode new exercise download not working

### ISSUE THREAD

**Issue by that-dumb** [rage/tmc-vscode#654]
**Describe the bug**
unable to download new exercises

**To Reproduce**
1. Go to TestMyCode
2. My Courses
3. Course Name
4. Choose Part
5. Download

**Expected behavior**
Downloads all selected courses

**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/61516647/186966868-8569696f-f3d8-4fff-9996-847f757263bf.png)
![Screenshot_2](https://user-images.githubusercontent.com/61516647/186966869-9cfc1415-8aa7-4c6d-a3db-f019abe522ab.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - VSCode Version [e.g. 1.4.0] 1.70.2
 - TMC Extension Version [e.g. 0.8.1] v2.1.3
 - Other related extensions.

**TMC Extension logs**
TMC -> Settings -> Set log level to verbose and reproduce error and paste logs.

**Additional context**

**Comment by Jeancoman** [comment]
I am having this exact same problem since the v2.1.3 updated, that is to say, since yesterday.

**Comment by jolampi** [comment]
Hello, thank you for bringing this issue to our attention. I have downgraded the dependency in question until this issue is resolved.

**Comment by jolampi** [comment]
Version 2.1.5 is now deployed with this issue fixed. Thank you again for reporting it. The issue was with an unexpected format change in a sub dependency.
