### ISSUE TITLE
Can't use extension, no commands are found

### ISSUE THREAD

**Issue by austinkassman** [rage/tmc-vscode#669]
Describe the bug: Can't login or use commands on TestMyCode Extension. Login page does not appear. All commands are not found when searching and running through the command search menu. 

To Reproduce
Steps to reproduce the behavior: Download the extension for TestMyCode and click into the extension. 

Expected behavior

Extension populates with a login page.

Desktop (please complete the following information):

OS: MacOS 12.3
VSCode Version 1.74.3 (Universal)
TMC Extension Version v2.1.5

TMC Extension logs
TMC -> Settings -> Set log level to verbose and reproduce error and paste logs.
I did set log level to verbose, unable to find any specific log files. Please let me know if there are additional instructions to provide more data.

Additional context

I followed the instructions from https://www.mooc.fi/en/installation/vscode/ to install Python, VSCode, and this extension. However when I click on the tab the entire menu is blank and no "log-in" information is available. 

I searched my commands to see if I could manually login but get a command not found error. This happens for all TestMyCode commands. 
Ex:
Command 'TestMyCode: Log In' resulted in an error (command 'tmc.login' not found)
Command 'TestMyCode: Welcome' resulted in an error (command 'tmc.showWelcome' not found)
Command 'TestMyCode: Action Menu' resulted in an error (command 'tmc.selectAction' not found)

I tried uninstalling and reinstalling Python, VS Code, and the extension, then restarting my computer and redownloading everything multiple times but that didn't work. I am able to use other extensions in vscode.

**Comment by austinkassman** [comment]
Tried checking these common Q&As to no avail: 
- Within VScode -> Preferences/Settings -> User ->  Features -> Extensions ->  Do you have Auto Check Updates ticked and Auto Update set to All Extensions? 
- Yes

-  On Mac, in Finder, go to ~/.vscode/extensions  Look for the extension folder, should be something like: moocfi.test-my-code-2.1.5
Are there any empty subfolders? Anything seem out of the ordinary from a quick glance?
- Nothing seems amiss. 

- Is VSCode installed in the "normal" location? Not trying to run it directly from the installer disk image? 
- Installed in my applications

**Comment by austinkassman** [comment]
I updated my MAC OS to 13.1 (22C65).
After removing the extension, removing vs code, redownloading vs code, and reinstalling the extension it still does not work. 

I used a friends old mac with an intel chip and he was able to download and see the login page under the TMC menu, as well as search for commands (command shift p) and run them. I checked out each of our extension folders and they look similar to me.

**Comment by austinkassman** [comment]
The TMC headers are not present next to my run code triangle button on the upper right hand side of TMC.

**Comment by austinkassman** [comment]
Please close this is the same issue as #640.

**Comment by aleksandrababenko91** [comment]
Do you find any solution?

**Comment by Heliozoa** [comment]
See the issue linked in the last comment before yours, #640, where the suggested solution is running `softwareupdate --install-rosetta`. If you're not on MacOS or the solution doesn't work, it's a new problem and you should open a new issue.
