### ISSUE TITLE
TMC menu does not show any options - Cannot run TMC commands

### ISSUE THREAD

**Issue by arvidkullhammar** [rage/tmc-vscode#675]
**Describe the bug**
When starting the TMC extension on VSCode, no menu options appear. 
When trying to log in by using the vs code command, an error appears: command 'tmc.login' not found

**To Reproduce**
1. Download the TMC extension
2. Start the TMC extension
3. No menu options appear

**Screenshots**
<img width="1470" alt="Screenshot 2023-07-13 at 11 51 18" src="https://github.com/rage/tmc-vscode/assets/91427561/bb688f86-c5e6-469d-80de-ac1a7e536059">
<img width="1470" alt="Screenshot 2023-07-13 at 11 51 51" src="https://github.com/rage/tmc-vscode/assets/91427561/d647e955-4e01-4d80-8c1c-8457dfab5a1c">

 - OS: OSX 13.4.1 
 - VSCode: 1.80.0
 - TMC Extension Version: 2.1.5
 
**Additional context**
This is my a new MBA m2. I have been able to use the extension on my MBP M1 work computer, and just wanted to continue the course on my new laptop.

**Comment by Joonas22** [comment]
I'm having the same issue in Windows 10. Error:

[2023-07-13 11:15:39:040] [ERROR] An error occurred while downloading TMC-langs:
Error — Request failed: Proxy Authentication Required — Error: Request failed: Proxy Authentication Required

**Comment by amemon0326** [comment]
Having the same error on my M2 MBA. 

https://github.com/rage/tmc-vscode/assets/69292203/973b1325-1df9-4413-a632-8aaaad967796

OS: OSX 12.5.1
VSCode: 1.80.0
TMC Extension Version: 2.1.5

**Comment by rjhefley** [comment]
VSCode: 
Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z (2 days ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

Running on OSX 12.5.1 M2 Max
I have the same problem as @amemon0326. Nothing will show up after installing TMC and selecting the button on the left pane.

Installed VSCode Insiders on Intel version and emulated through roseta and it works fine. 

Please provide a solution for us Mac Silicon folks! Really enjoying these MOOC.FI courses.

Thanks!

**Comment by Heliozoa** [comment]
Sorry for the late response, I was on holiday until recently. I'm doing some work on the extension, but unfortunately we don't have any M2 Macs available for testing so I can't replicate the issue or confirm whether any changes I make fix it or not. I'm improving the logging either way so if this doesn't get fixed in the next update, hopefully we'll be able to get some logs that help identify this issue.

@Joonas22 This looks like a separate problem, you can make a new issue for it.

**Comment by rjhefley** [comment]
> Sorry for the late response, I was on holiday until recently. I'm doing some work on the extension, but unfortunately we don't have any M2 Macs available for testing so I can't replicate the issue or confirm whether any changes I make fix it or not. I'm improving the logging either way so if this doesn't get fixed in the next update, hopefully we'll be able to get some logs that help identify this issue.
> 
> @Joonas22 This looks like a separate problem, you can make a new issue for it.

Thank you so much for the response! Please let us know how we can help test once ready! :)
Luckily I still have other machines to do the MOOC on, but this new M2 is a new shiny toy that I can't wait to fully switch over to soon! LOL

**Comment by Heliozoa** [comment]
Hi,
We just released a new pre-release version of the extension that may fix this issue. You can try it out by right-clicking the extension in the extensions menu and selecting "Switch to Pre-Release Version".

![demo](https://github.com/rage/tmc-vscode/assets/15956940/80215a7e-1ea0-4392-82f3-d099776975c2)
