### ISSUE TITLE
TMC not working after newest version (v.2.2.2) - temporary fix included

### ISSUE THREAD

**Issue by repenaattori** [rage/tmc-vscode#692]
**Describe the bug**
Some of my students got the problem that TMC stopped working when the new extension version was published for VS Code. The "There is no data provider registered that can provide view data" is left pending and TMC from Command palette gives an error:

**To Reproduce**
1. Update the latest extension version v. 2.2.2
2. Go to TMC extension tab

**Expected behavior**
The current added courses and basic TMC options are visible

**Screenshots**
![image](https://github.com/rage/tmc-vscode/assets/111489375/3c27b93c-124f-4f7e-9670-4ad8f0342bfb)

![image](https://github.com/rage/tmc-vscode/assets/111489375/71e0021c-eb74-4155-ba7d-289742c85840)

**Desktop (please complete the following information):**
 - Windows 11 at least
 - VS Code 1.82.2
 - TMC v2.2.2

**TMC Extension logs**
Unfortunately unable to reproduce this problem in my own computer after doing a temporary fix. If getting the log from students, adding it here later.

**Additional context**
I've found two temporary solution that might work. First one is to delete the extension directory in computers globalStorage-directory and reinstall plugin. Another solution was to install the version 2.1.5 and then reinstall the 2.2.2. Downgrading to 2.2.1 did not work.

**Comment by Heliozoa** [comment]
Sorry for the trouble. The error seems to indicate that the extension failed to activate, and while there are many reasons for why that might randomly happen (e.g. network issues) I don't have any ideas for why the version update would cause it. If you can provide logs later with some error message, that would be great.

**Comment by repenaattori** [comment]
Unfortunately I'm probably not able to get any logs for this. We've used the previously mentioned solution for all the students that had the problem and now everyone has updated the newest version. Rolling back to older and then back to the new one won't reproduce the problem. But as from now on the newest version is installed, in the future courses the problem should not exist anymore.
