### ISSUE TITLE
"File system provider for ... is not available" when changing exercises location

### ISSUE THREAD

**Issue by funkey7dan** [rage/tmc-vscode#706]
**Describe the bug**
When trying to change the path of the TMC Exercises Location an error is show with the text: "File system provider for C:%5CUsers%5Cfunke%5CAppData%5CLocal%5Ctmc%5Cvscode is not available." and no option to proceed further.

**To Reproduce**
1. Install the extension
2. go to the extension in vscode
3. press "Change path" button. alternatively 

**Expected behavior**
An fs navigator for changing the save location should be presented.

**Desktop (please complete the following information):**
 - OS: Win10
 - VSCode Version 1.85.1
 - TMC Extension Version 2.2.4

**TMC Extension logs**
[2024-01-08 07:15:03:446] [DEBUG] Received message
{"type":"changeTmcDataPath"}
[2024-01-08 07:15:03:447] [INFO] Changing TMC data path

**Additional context**
First time installing the extension.

**Comment by data-hammy** [comment]
Same issue for me

**Comment by Heliozoa** [comment]
Sorry for the slow response and thanks for the report. This will be fixed in the next release which should be released this week.

**Comment by Heliozoa** [comment]
This should be fixed in the prerelease version `v3.0.1`. You can switch to the pre-release version from the extension's page by clicking "Switch to Pre-Release Version" here:

![image](https://github.com/rage/tmc-vscode/assets/15956940/5d364779-2a61-4175-a740-e153b9ac59de)

If you give it a try, let me know if it fixes the issue and if you experience any other problems with it.

**Comment by data-hammy** [comment]
I don't have the Switch to Pre-Release version button

**Comment by funkey7dan** [comment]
> I don't have the Switch to Pre-Release version button

I found this in the extensions (The tab for installing new extensions)
Switching to pre-release fixed the issue for me, thanks @Heliozoa !
