### ISSUE TITLE
TMC does not work for VC

### ISSUE THREAD

**Issue by Motharatti-Schoolacc** [rage/tmc-vscode#716]
**Describe the bug**
Nothing appears if you open the tab for tmc
![image](https://github.com/rage/tmc-vscode/assets/167402113/52b4cdaa-f3ea-4e4a-b0d7-2e10666c00f8)

**To Reproduce**
install tmc
open tmc tab
Empty.

**Comment by Heliozoa** [comment]
I wasn't able to replicate this issue. From the screenshot I see that you're using `v2.2.4` which isn't the latest version. Try installing the latest version from the dropdown menu in the arrow of the 
`Uninstall` button:

![image](https://github.com/rage/tmc-vscode/assets/15956940/8e270682-0dda-4299-8037-2327547bd180)

If you can't find `v3.0.3` there might be something wrong with the way your VSCode is set up. In that case, if you can post the information from the `Help` -> `About` menu from the top bar it may be helpful.

You can also check the extension logs by selecting `View` -> `Output` from the top bar and selecting `TestMyCode` from the dropdown menu near the bottom of the window? There should be relevant information in there. 
![image](https://github.com/rage/tmc-vscode/assets/15956940/7a20d715-9c7d-4c3a-b41a-a69841f13c58)

**Comment by Heliozoa** [comment]
I wasn't able to replicate this issue. From the screenshot I see that you're using `v2.2.4` which isn't the latest version. Try installing the latest version from the dropdown menu in the arrow of the 
`Uninstall` button:

![image](https://github.com/rage/tmc-vscode/assets/15956940/e03af41a-7f44-40c4-88f2-ac8052077b4b)


If you can't find `v3.0.3` there might be something wrong with the way your VSCode is set up. In that case, if you can post the information from the `Help` -> `About` menu from the top bar it may be helpful.

You can also check the extension logs by selecting `View` -> `Output` from the top bar and selecting `TestMyCode` from the dropdown menu near the bottom of the window? There should be relevant information in there. 

![image](https://github.com/rage/tmc-vscode/assets/15956940/d9a66f54-29b0-44d7-afba-21678ada3960)

**Comment by Motharatti-Schoolacc** [comment]
![image](https://github.com/rage/tmc-vscode/assets/167402113/cc2c184d-2c04-4d35-98b4-403f4ad47f2a)
I can't see the 3.0.3 version but i don't know how i set up VSCode wrong how would i fix it?

**Comment by Heliozoa** [comment]
It looks like you're on an old version of VS Code. 1.73.1 was released in 2022 and the latest version 1.88.1 was released this month.

I think the latest version of the extension isn't visible because it requires at least 1.75.0. Unfortunately there doesn't seem to be any indication of this in the VS Code extension UI...

Try updating VS Code by selecting `Help` -> `Check for updates` in the top bar or reinstalling it from https://code.visualstudio.com/

**Comment by Motharatti-Schoolacc** [comment]
That worked thanks
