### ISSUE TITLE
111 File with seemingly no explanation?

### ISSUE THREAD

**Issue by JuhaJGamer** [rage/tmc-vscode#717]
**Describe the bug**
In `~/.config/Code - OSS/User/globalStorage/moocfi.test-my-code/cli/` there exists a single file, seemingly an executable. It has 111 permissions. This is stupid. There is absolutely no reason why a file should ever have 111 permissions. More importantly, it breaks things. Most people assume that 111 files don't exist, that the theoretical existence of 111 files is simply a side-effect of simplicity in design for the permissions system of computers in the 70's. Having unreadable files show up in their home folder is unexpected behaviour for most people and they do not want it to happen to them. This is clear by my backup system's snapshot log, which now contains around one month's worth of attempted snapshots every 15 minutes, each failing with a very unexpected error despite running as superuser. You should not have unreadable files created by user extensions in your home folder. 

**To Reproduce**
1. Install the extension
2. Open a terminal and navigate to `~/.config/Code - OSS/User/globalStorage/moocfi.test-my-code/cli/`
3. Run `ls -l`

**Expected behavior**
Not having universally unreadable executables floating around your home folder.

**Desktop (please complete the following information):**
 - OS: Linux x64 6.9.9-arch1-1
 - VSCode Version: 1.91.1
 - TMC Extension Version: 3.0.2

**TMC Extension logs**
Attached
[1-TestMyCode.log](https://github.com/user-attachments/files/16419707/1-TestMyCode.log)

**Comment by Heliozoa** [comment]
Thanks for the issue, this has been fixed in v3.0.4 that was released today.
